#!/usr/bin/env python3
""" Gadget-code generator for QEMU TCTI on AArch64. 

Generates a C-code include file containing 'gadgets' for use by TCTI.
"""

import os
import sys
import itertools

# Epilogue code follows at the end of each gadget, and handles continuing execution.
EPILOGUE = ( 
    # Load our next gadget address from our bytecode stream, advancing it.
    "ldr x27, [x28], #8",

    # Jump to the next gadget.
    "br x27"
)

# The number of general-purpose registers we're affording the TCG. This must match
# the configuration in the TCTI target.
TCG_REGISTER_COUNT   = 16
TCG_REGISTER_NUMBERS = list(range(TCG_REGISTER_COUNT))

# The host register behind each TCG register. R0-R7 must stay x0-x7, the
# argument registers the call gadget hands to C; R14 (env) and R15 (the call
# stack) are fixed too. R8-R12 live in x19-x23, which C preserves across a
# call: TCTI then marks them call-saved, so values TCG keeps there survive
# helper calls and guest memory accesses (whose slow paths call C) instead
# of being spilled and reloaded around every one.
HOST_REGISTER = {n: n for n in TCG_REGISTER_NUMBERS}
HOST_REGISTER.update({8: 19, 9: 20, 10: 21, 11: 22, 12: 23})

# Helper that provides each of the AArch64 condition codes of interest.
ARCH_CONDITION_CODES = ["eq", "ne", "lt", "ge", "le", "gt", "lo", "hs", "ls", "hi"]

# The list of vector size codes supported on this platform.
VECTOR_SIZES = ['16b', '8b', '4h', '8h', '2s', '4s', '2d']

# The MMU indices we create TLB fast-path gadgets for. Each gadget loads its
# CPUTLBDescFast from a fixed offset from env, and that offset depends on the
# MMU index and on the layout of CPUNegativeOffsetState, so the offset is
# computed by the C compiler (TCTI_TLB_FAST_OFS, in tcti-gadget-defs.h) rather
# than written down here. An access to any other index takes the slow path.
#
# 0-5 are x86's kernel, user and no-SMAP modes, in 64- and 32-bit flavours:
# everything generated code uses. This must match TCTI_TLB_FAST_MMU_INDICES in
# tcti-gadget-defs.h.
QEMU_TLB_FAST_MMU_INDICES = range(6)

# Statistics.
gadgets      = 0
instructions = 0

# Files to write to.
current_collection = "basic"
output_files = {}

# Everything is written to the directory named on the command line: meson
# passes the build directory the outputs are expected in.
output_dir = sys.argv[1] if len(sys.argv) > 1 else "tcg"

# Create a top-level header.
top_header = open(f"{output_dir}/tcti_gadgets.h", "w")
print("/* Automatically generated by tcti-gadget-gen.py. Do not edit. */\n", file=top_header)

def _get_output_files():
    """ Gathers the output C and H files for a given gadget-cluster name. """

    # If we don't have an output file for this already, create it.
    return output_files[current_collection]


def START_COLLECTION(name, needs_defs=False):
    """ Sets the name of the current collection.

    needs_defs includes tcti-gadget-defs.h, for gadgets whose operands are
    computed from QEMU's own structures.
    """

    global current_collection

    # If we already have a collection for this, skip it.
    if name in output_files:
        return

    # Create the relevant output files
    new_c_file = open(f"{output_dir}/tcti_{name}_gadgets.c", "w")
    new_h_file = open(f"{output_dir}/tcti_{name}_gadgets.h", "w")
    output_files[name] = (new_c_file, new_h_file)

    # Add the file to our gadget collection.
    print(f'#include "tcti_{name}_gadgets.h"', file=top_header)

    # Add generated messages to the relevant collection.
    print("/* Automatically generated by tcti-gadget-gen.py. Do not edit. */\n", file=new_c_file)
    print("/* Automatically generated by tcti-gadget-gen.py. Do not edit. */\n", file=new_h_file)

    # Start our C file with inclusion of the relevant header.
    if needs_defs:
        print('\n#include "tcti-gadget-defs.h"', file=new_c_file)
    print(f'\n#include "tcti_{name}_gadgets.h"\n', file=new_c_file)

    # Start our H file with a simple pragma-guard, for speed.
    print('\n#pragma once\n', file=new_h_file)

    # Finally, set the global active collection.
    current_collection = name
    

def simple(name, *lines, export=True, operands=None):
    """ Generates a simple gadget that needs no per-register specialization.

    operands, if given, is the input-operand list of an extended asm statement,
    for gadgets that take a compile-time constant from C: "i" constraints only,
    as a naked function has no registers to give an operand.
    """

    global gadgets, instructions

    gadgets += 1

    # Fetch the files we'll be using for output.
    c_file, h_file = _get_output_files()

    # Create our C/ASM framing.
    if export:
        print(f"__attribute__((naked)) void gadget_{name}(void);", file=h_file)
        print(f"__attribute__((naked)) void gadget_{name}(void)", file=c_file)
    else:
        print(f"static __attribute__((naked)) void gadget_{name}(void)", file=c_file)

    print("{", file=c_file)

    # Add the core gadget
    print("\tasm(", file=c_file)
    for line in lines + EPILOGUE:
        print(f"\t\t\"{line} \\n\"", file=c_file)
        instructions += 1
    if operands:
        print(f"\t\t:: {operands}", file=c_file)
    print("\t);", file=c_file)

    # End our framing.
    print("}\n", file=c_file)



def with_register_substitutions(name, substitutions, *lines, immediate_range=range(0), filter=lambda p: False, operands=None):
    """ Generates a collection of gadgtes with register substitutions. """

    def _expand_op1_immediate(num):
        """ Gets a uncompressed bitfield argument for a given immediate; for NEON instructions. 
        
        Duplciates each bit eight times; converting 0b0100 to 0x00FF0000.
        """

        # Get the number as a binary string...
        binstring = bin(num)[2:]

        # ... expand out the values to hex...
        hex_string = binstring.replace('1', 'FF').replace('0', '00') 

        # ... and return out the new constant.
        return f"0x{hex_string}"


    def substitutions_for_letter(letter, number, line):
        """ Helper that transforms Wd => w1, implementing gadget substitutions. """

        # Register substitutions...
        host = HOST_REGISTER.get(number, number)
        line = line.replace(f"X{letter}", f"x{host}")
        line = line.replace(f"W{letter}", f"w{host}")

        # ... vector register substitutions...
        line = line.replace(f"V{letter}", f"v{number + 16}")
        line = line.replace(f"D{letter}", f"d{number + 16}")
        line = line.replace(f"Q{letter}", f"q{number + 16}")

        # ... regular immediate substitutions...
        line = line.replace(f"I{letter}", f"{number}")

        # ... and compressed immediate substitutions.
        line = line.replace(f"S{letter}", f"{_expand_op1_immediate(number)}")
        return line

        
    # Build a list of all the various stages we'll iterate over...
    immediate_parameters = list(immediate_range)
    parameters   = ([TCG_REGISTER_NUMBERS] * len(substitutions))

    # ... adding immediates, if need be.
    if immediate_parameters:
        parameters.append(immediate_parameters)
        substitutions = substitutions + ['i']

    # Generate a list of register-combinations we'll support.
    permutations = itertools.product(*parameters)

    #  For each permutation...
    for permutation in permutations:
        # Filter any invalid combination
        if filter(permutation): 
            continue

        new_lines = lines

        # Replace each placeholder element with its proper value...
        for index, element in enumerate(permutation):
            letter = substitutions[index]
            number = element

            # Create new gadgets for the releavnt line...
            new_lines = [substitutions_for_letter(letter, number, line) for line in new_lines]

        # ... and emit the gadget.
        permutation_id = "_arg".join(str(number) for number in permutation)
        simple(f"{name}_arg{permutation_id}", *new_lines, export=False, operands=operands)


def with_dnm(name, *lines):
    """ Generates a collection of gadgets with substitutions for Xd, Xn, and Xm, and equivalents. """
    with_register_substitutions(name, ("d", "n", "m"), *lines)

    # Fetch the files we'll be using for output.
    c_file, h_file = _get_output_files()

    # Print out an extern.
    print(f"extern const void* gadget_{name}[{TCG_REGISTER_COUNT}][{TCG_REGISTER_COUNT}][{TCG_REGISTER_COUNT}];", file=h_file)

    # Print out an array that contains all of our gadgets, for lookup.
    print(f"const void* gadget_{name}[{TCG_REGISTER_COUNT}][{TCG_REGISTER_COUNT}][{TCG_REGISTER_COUNT}] = ", end="", file=c_file)
    print("{", file=c_file)

    # D array
    for d in TCG_REGISTER_NUMBERS:
        print("\t{", file=c_file)

        # N array
        for n in TCG_REGISTER_NUMBERS:
            print("\t\t{", end="", file=c_file)

            # M array
            for m in TCG_REGISTER_NUMBERS:
                print(f"gadget_{name}_arg{d}_arg{n}_arg{m}", end=", ", file=c_file)

            print("},", file=c_file)
        print("\t},", file=c_file)
    print("};", file=c_file)


def with_dn_immediate(name, *lines, immediate_range, filter=lambda m: False):
    """ Generates a collection of gadgets with substitutions for Xd, Xn, and Xm, and equivalents. """
    with_register_substitutions(name, ["d", "n"], *lines, immediate_range=immediate_range, filter=lambda p: filter(p[-1]))

    # Fetch the files we'll be using for output.
    c_file, h_file = _get_output_files()

    # Print out an extern.
    print(f"extern const void* gadget_{name}[{TCG_REGISTER_COUNT}][{TCG_REGISTER_COUNT}][{len(immediate_range)}];", file=h_file)

    # Print out an array that contains all of our gadgets, for lookup.
    print(f"const void* gadget_{name}[{TCG_REGISTER_COUNT}][{TCG_REGISTER_COUNT}][{len(immediate_range)}] = ", end="", file=c_file)
    print("{", file=c_file)

    # D array
    for d in TCG_REGISTER_NUMBERS:
        print("\t{", file=c_file)

        # N array
        for n in TCG_REGISTER_NUMBERS:
            print("\t\t{", end="", file=c_file)

            # M array
            for i in immediate_range:
                if filter(i):
                    print(f"(void *)0", end=", ", file=c_file)
                else:
                    print(f"gadget_{name}_arg{d}_arg{n}_arg{i}", end=", ", file=c_file)

            print("},", file=c_file)
        print("\t},", file=c_file)
    print("};", file=c_file)


def with_pair(name, substitutions, *lines, operands=None):
    """ Generates a collection of gadgets with two subtstitutions."""
    with_register_substitutions(name, substitutions, *lines, operands=operands)

    # Fetch the files we'll be using for output.
    c_file, h_file = _get_output_files()

    print(f"extern const void* gadget_{name}[{TCG_REGISTER_COUNT}][{TCG_REGISTER_COUNT}];", file=h_file)

    # Print out an array that contains all of our gadgets, for lookup.
    print(f"const void* gadget_{name}[{TCG_REGISTER_COUNT}][{TCG_REGISTER_COUNT}] = ", end="", file=c_file)
    print("{", file=c_file)

    # N array
    for a in TCG_REGISTER_NUMBERS:
        print("\t\t{", end="", file=c_file)

        # M array
        for b in TCG_REGISTER_NUMBERS:
            print(f"gadget_{name}_arg{a}_arg{b}", end=", ", file=c_file)

        print("},", file=c_file)
    print("};", file=c_file)


def math_dnm(name, mnemonic):
    """ Equivalent to `with_dnm`, but creates a _i32 and _i64 variant. For simple math. """
    with_dnm(f'{name}_i32', f"{mnemonic} Wd, Wn, Wm")
    with_dnm(f'{name}_i64', f"{mnemonic} Xd, Xn, Xm")

def math_dni(name, mnemonic):
    """ A _i32 and _i64 op on Xn and an immediate from the gadget stream,
    so an op with a constant operand is one dispatch instead of a movi and
    the op. """
    with_dn(f'{name}_i32', "ldr x27, [x28], #8", f"{mnemonic} Wd, Wn, w27")
    with_dn(f'{name}_i64', "ldr x27, [x28], #8", f"{mnemonic} Xd, Xn, x27")

def math_dn(name, mnemonic, source_is_wn=False):
    """ Equivalent to `with_dn`, but creates a _i32 and _i64 variant. For simple math. """
    with_dn(f'{name}_i32', f"{mnemonic} Wd, Wn")
    with_dn(f'{name}_i64', f"{mnemonic} Xd, Wn" if source_is_wn else f"{mnemonic} Xd, Xn")


def with_nm(name, *lines):
    """ Generates a collection of gadgets with substitutions for Xn, and Xm, and equivalents. """
    with_pair(name, ('n', 'm',), *lines)


def with_dn(name, *lines, operands=None):
    """ Generates a collection of gadgets with substitutions for Xd, and Xn, and equivalents. """
    with_pair(name, ('d', 'n',), *lines, operands=operands)


def ldst_dn(name, *lines):
    """ Generates a collection of gadgets with substitutions for Xd, and Xn, and equivalents. 
    
    This variant is optimized for loads and stores, and optimizes common offset cases.
    """

    #
    # Simple case: create our gadgets.
    #
    with_dn(name, "ldr x27, [x28], #8", *lines)

    #
    # Optimization case: create variants of our gadgets with our offsets replaced with common immediates.
    #
    immediate_lines_pos = [line.replace("x27", "#Ii") for line in lines]
    with_dn_immediate(f"{name}_imm", *immediate_lines_pos, immediate_range=range(64))

    immediate_lines_aligned = [line.replace("x27", "#(Ii << 3)") for line in lines]
    with_dn_immediate(f"{name}_sh8_imm", *immediate_lines_aligned, immediate_range=range(64))

    immediate_lines_neg = [line.replace("x27", "#-Ii") for line in lines]
    with_dn_immediate(f"{name}_neg_imm", *immediate_lines_neg, immediate_range=range(64))


def with_single(name, substitution, *lines, operands=None):
    """ Generates a collection of gadgets with two subtstitutions."""
    with_register_substitutions(name, (substitution,), *lines,
                                operands=operands)

    # Fetch the files we'll be using for output.
    c_file, h_file = _get_output_files()

    print(f"extern const void* gadget_{name}[{TCG_REGISTER_COUNT}];", file=h_file)

    # Print out an array that contains all of our gadgets, for lookup.
    print(f"const void* gadget_{name}[{TCG_REGISTER_COUNT}] = ", end="", file=c_file)
    print("{", file=c_file)

    for n in TCG_REGISTER_NUMBERS:
        print(f"gadget_{name}_arg{n}", end=", ", file=c_file)

    print("};", file=c_file)


def with_d_immediate(name, *lines, immediate_range=range(0)):
    """ Generates a collection of gadgets with two subtstitutions."""
    with_register_substitutions(name, ['d'], *lines, immediate_range=immediate_range)

    # Fetch the files we'll be using for output.
    c_file, h_file = _get_output_files()

    print(f"extern void* gadget_{name}[{TCG_REGISTER_COUNT}][{len(immediate_range)}];", file=h_file)

    # Print out an array that contains all of our gadgets, for lookup.
    print(f"void* gadget_{name}[{TCG_REGISTER_COUNT}][{len(immediate_range)}] = ", end="", file=c_file)
    print("{", file=c_file)

    # D array
    for a in TCG_REGISTER_NUMBERS:
        print("\t\t{", end="", file=c_file)

        # I array
        for b in immediate_range:
            print(f"gadget_{name}_arg{a}_arg{b}", end=", ", file=c_file)

        print("},", file=c_file)
    print("};", file=c_file)



def with_d(name, *lines):
    """ Generates a collection of gadgets with substitutions for Xd. """
    with_single(name, 'd', *lines)


# Assembly code for saving our machine state before entering the C runtime.
C_CALL_PROLOGUE = [
    "stp x14, x15, [sp, #-16]!",
    "stp x28, lr,  [sp, #-16]!",
]

# Assembly code for restoring our machine state after leaving the C runtime.
C_CALL_EPILOGUE = [
    "ldp x28, lr,  [sp], #16",
    "ldp x14, x15, [sp], #16",
]


def create_tlb_fastpath(is_aligned, is_write, miss_label="0", size=8):
    """ Creates a set of instructions that perform a soft-MMU TLB lookup.

    This is used for `qemu_ld`/qemu_st` instructions; to emit a prologue that
    hopefully helps us skip a slow call into the C runtime when a Guest Virtual 
    -> Host Virtual mapping is in the softmmu's TLB.

    This "fast-path" prelude behaves as follows:
        - If a TLB entry is found for the address stored in Xn, then x27
          is stored to an "addend" that can be added to the guest virtual addres
          to get the host virtual address (the address in our local memory space).
        - If a TLB entry isn't found, it branches to the "miss_label" (by default, 0:),
          so address lookup can be handled by the fastpath.

    Clobbers x24, and x26; provides output in x27.
    """

    fast_path = [
        # Load env_tlb(env)->f[mmu_idx].{mask,table} into {x26,x27}. The
        # offset is the gadget's asm operand; see tlb_operands().
        "ldp x26, x27, [x14, %[tlb_ofs]]",

        # Extract the TLB index from the address into X26, as tlb_index()
        # does: the page number with the bits from CPU_TLB_INDEX_FOLD (8) up
        # folded in. x24 is free until the comparison below.
        "eor x24, Xn, Xn, lsr #8", # Xn = addr register
        "and x26, x26, x24, lsr #7",

        # Add the tlb_table pointer, creating the CPUTLBEntry address into X27. 
        "add x27, x27, x26",

        # Load the tlb comparator into X26, and the fast path addend into X27. 
        "ldr x26, [x27, #8]" if is_write else "ldr x26, [x27]",
        "ldr x27, [x27, #0x18]",

    ]

    if is_aligned:
        fast_path.extend([
            # Store the page mask part of the address into X24.
            "and x24, Xn, #0xfffffffffffff000",

            # Compare the masked address with the TLB value.
            "cmp x26, x24",

            # If we're not equal, this isn't a TLB hit. Jump to our miss handler.
            f"b.ne {miss_label}f",
        ])
    else:
        fast_path.extend([
            # If we're not aligned, add in our alignment value to ensure we don't
            # don't straddle the end of a page.
            f"add x24, Xn, #{size - 1}",

            # Store the page mask part of the address into X24.
            "and x24, x24, #0xfffffffffffff000",

            # Compare the masked address with the TLB value.
            "cmp x26, x24",

            # If we're not equal, this isn't a TLB hit. Jump to our miss handler.
            f"b.ne {miss_label}f",
        ])

    return fast_path



def tlb_operands(mmu_idx):
    """ The asm operand list for a fast-path gadget serving mmu_idx. """
    return f'[tlb_ofs] "i" (TCTI_TLB_FAST_OFS({mmu_idx}))'


def granule_check(size):
    """ For an ordered access of size bytes, not known to be aligned: branches
    to the slow path if it crosses a 16-byte boundary, where an LDAPR or STLR
    faults even with LSE2. That is, if (addr & 15) > 16 - size. """
    if size == 1:
        return []
    return [
        "and x26, Xn, #15",
        f"cmp x26, #{16 - size}",
        "b.hi 0f",
    ]


def ld_thunk(name, fastpath_32b, fastpath_64b, slowpath_helper, immediate=None, is_aligned=False, force_slowpath=False, ordered=None):
    """ Creates a thunk into our C runtime for a QEMU LD operation.

    ordered, if given, is the access size in bytes: the fast path is then
    the given LDAPR sequence (on x27, the host address), after a check that
    the access does not cross a 16-byte boundary, and the slow path orders
    the helper's plain load after it, as an LDAPR would be. """

    # A slow-path gadget serves every MMU index, so there is just the one;
    # otherwise there is one per index with a fast path.
    indices = [None] if force_slowpath else QEMU_TLB_FAST_MMU_INDICES
    for mmu_idx in indices:
        suffix = "any" if mmu_idx is None else f"idx{mmu_idx}"
        operands = None if mmu_idx is None else tlb_operands(mmu_idx)

        for is_32b in (True, False):
            fastpath = fastpath_32b if is_32b else fastpath_64b

            gadget_name = f"{name}_{suffix}_i32" if is_32b else f"{name}_{suffix}_i64"
            postscript = () if immediate else ("add x28, x28, #8",)

            # If we have a pure-assembly fast path, start our gadget with it.
            if fastpath and not force_slowpath:
                fastpath_ops = [
                    # Create a fastpath that jumps to miss_lable on a TLB miss,
                    # or sets x27 to the TLB addend on a TLB hit.
                    *create_tlb_fastpath(is_aligned=is_aligned, is_write=False),
                    # LDAPR is FEAT_LRCPC (ARMv8.3), past what we may be built for.
                    *(granule_check(ordered) + ["add x27, x27, Xn", ".arch_extension rcpc"] if ordered else []),

                    # On a hit, we can just perform an appropriate load...
                    *fastpath,

                    # Run our patch-up post-script, if we have one.
                    *postscript,

                    # ... and then we're done!
                    *EPILOGUE,
                ]
            # Otherwise, we'll save arguments for our slow path.
            else:
                fastpath_ops = []

            #
            # If we're not taking our fast path, we'll call into our C runtime to take the slow path.
            # 
            with_dn(gadget_name, 
                    *fastpath_ops,

                "0:",
                    "mov x27, Xn",

                    # Save our registers in preparation for entering a C call.
                    *C_CALL_PROLOGUE,

                    # Per our calling convention:
                    # - Move our architectural environment into x0, from x14.
                    # - Move our target address into x1. [Placed in x27 below.]
                    # - Move our operation info into x2, from an immediate32.
                    # - Move the next bytecode pointer into x3, from x28.
                    "mov   x0, x14",
                    "mov   x1, x27",
                    f"mov   x2, #{immediate}" if (immediate is not None) else "ldr   x2, [x28], #8", 
                    "mov   x3, x28",

                    # Perform our actual core code.
                    f"bl _{slowpath_helper}",

                    # Temporarily store our result in a register that won't get trashed.
                    "mov x27, x0",

                    # Restore our registers after our C call.
                    *C_CALL_EPILOGUE,
                    *(["dmb ishld"] if ordered else []),

                    # Finally, call our postscript...
                    *postscript,

                    # ... and place our results in the target register.
                    "mov Wd, w27" if is_32b else "mov Xd, x27",
                operands=operands,
            )


def st_thunk(name, fastpath_32b, fastpath_64b, slowpath_helper, immediate=None, is_aligned=False, force_slowpath=False, ordered=None):
    """ Creates a thunk into our C runtime for a QEMU ST operation.

    ordered is as for ld_thunk, with STLR; the slow path orders the helper's
    plain store after earlier stores, as an STLR would be. """

    # As for ld_thunk.
    indices = [None] if force_slowpath else QEMU_TLB_FAST_MMU_INDICES
    for mmu_idx in indices:
        suffix = "any" if mmu_idx is None else f"idx{mmu_idx}"
        operands = None if mmu_idx is None else tlb_operands(mmu_idx)

        for is_32b in (True, False):
            fastpath = fastpath_32b if is_32b else fastpath_64b

            gadget_name = f"{name}_{suffix}_i32" if is_32b else f"{name}_{suffix}_i64"
            postscript = () if immediate else ("add x28, x28, #8",)

            # If we have a pure-assembly fast path, start our gadget with it.
            if fastpath and not force_slowpath:
                fastpath_ops = [

                    # Create a fastpath that jumps to miss_lable on a TLB miss,
                    # or sets x27 to the TLB addend on a TLB hit.
                    *create_tlb_fastpath(is_aligned=is_aligned, is_write=True),
                    *(granule_check(ordered) + ["add x27, x27, Xn"] if ordered else []),

                    # On a hit, we can just perform an appropriate load...
                    *fastpath,

                    # Run our patch-up post-script, if we have one.
                    *postscript,

                    # ... and then we're done!
                    *EPILOGUE,
                ]
            else:
                fastpath_ops = []


            #
            # If we're not taking our fast path, we'll call into our C runtime to take the slow path.
            # 
            with_dn(gadget_name, 
                    *fastpath_ops,

                "0:",
                    # Move our arguments into registers that we're not actively using.
                    # This ensures that they won't be trounced by our calling convention
                    # if this is reading values from x0-x4.
                    "mov w27, Wd" if is_32b else "mov x27, Xd",
                    "mov x26, Xn",

                    # Save our registers in preparation for entering a C call.
                    *C_CALL_PROLOGUE,

                    # Per our calling convention:
                    # - Move our architectural environment into x0, from x14.
                    # - Move our target address into x1. [Moved into x26 above].
                    # - Move our target value into x2. [Moved into x27 above].
                    # - Move our operation info into x3, from an immediate32.
                    # - Move the next bytecode pointer into x4, from x28.
                    "mov   x0, x14",
                    "mov   x1, x26",
                    "mov   x2, x27",
                    f"mov  x3, #{immediate}" if (immediate is not None) else "ldr   x3, [x28], #8", 
                    "mov   x4, x28",
                    *(["dmb ishst"] if ordered else []),

                    # Perform our actual core code.
                    f"bl _{slowpath_helper}",

                    # Restore our registers after our C call.
                    *C_CALL_EPILOGUE,

                    # Finally, call our postscript.
                    *postscript,
                operands=operands,
            )



def vector_dn(name, *lines):
    """ Creates a set of gadgets for every size of a given vector op. Accepts 'S' as a size placeholder. """

    def do_size_replacement(line, size):
        line = line.replace(".S", f".{size}")
        
        # If this size requires a 32b register, replace Wd with Xd.
        if size == "2d":
            line = line.replace("Wn", "Xn")

        return line


    # Create a variant for each size, replacing any placeholders.
    for size in VECTOR_SIZES:
        sized_lines = (do_size_replacement(line, size) for line in lines)
        with_dn(f"{name}_{size}", *sized_lines)


def vector_dnm(name, *lines, scalar=None, omit_sizes=()):
    """ Creates a set of gadgets for every size of a given vector op. Accepts 'S' as a size placeholder. """

    def do_size_replacement(line, size):
        return line.replace(".S", f".{size}")
        
    # Create a variant for each size, replacing any placeholders.
    for size in VECTOR_SIZES:
        if size in omit_sizes:
            continue

        sized_lines = (do_size_replacement(line, size) for line in lines)
        with_dnm(f"{name}_{size}", *sized_lines)

    if scalar:
        if isinstance(scalar, str):
            sized_lines = (scalar,)
        with_dnm(f"{name}_scalar", *sized_lines)

def vector_dn_immediate(name, *lines, scalar=None, immediate_range, omit_sizes=(), filter=lambda s, m: False):
    """ Creates a set of gadgets for every size of a given vector op. Accepts 'S' as a size placeholder. """

    def do_size_replacement(line, size):
        return line.replace(".S", f".{size}")
        
    # Create a variant for each size, replacing any placeholders.
    for size in VECTOR_SIZES:
        if size in omit_sizes:
            continue

        sized_lines = (do_size_replacement(line, size) for line in lines)
        with_dn_immediate(f"{name}_{size}", *sized_lines, immediate_range=immediate_range, filter=lambda m: filter(size, m))

    if scalar:
        if isinstance(scalar, str):
            sized_lines = (scalar,)
        with_dn_immediate(f"{name}_scalar", *sized_lines, immediate_range=immediate_range, filter=lambda m: filter(None, m))

def vector_math_dnm(name, operation):
    """ Generates a collection of gadgets for vector math instructions. """
    vector_dnm(name, f"{operation} Vd.S, Vn.S, Vm.S", scalar=f"{operation} Dd, Dn, Dm")


def vector_math_dnm_no64(name, operation):
    """ Generates a collection of gadgets for vector math instructions. """
    vector_dnm(name, f"{operation} Vd.S, Vn.S, Vm.S", omit_sizes=('2d',))


def vector_logic_dn(name, operation):
    """ Generates a pair of gadgets for vector bitwise logic instructions. """
    with_dn(f"{name}_d", f"{operation} Vd.8b, Vn.8b")
    with_dn(f"{name}_q", f"{operation} Vd.16b, Vn.16b")


def vector_logic_dnm(name, operation):
    """ Generates a pair of gadgets for vector bitwise logic instructions. """
    with_dnm(f"{name}_d", f"{operation} Vd.8b, Vn.8b, Vm.8b")
    with_dnm(f"{name}_q", f"{operation} Vd.16b, Vn.16b, Vm.16b")

def vector_math_dn_immediate(name, operation, immediate_range, filter=lambda x: False):
    """ Generates a collection of gadgets for vector math instructions. """
    vector_dn_immediate(name, f"{operation} Vd.S, Vn.S, #Ii", scalar=f"{operation} Dd, Dn, #Ii", immediate_range=immediate_range, filter=filter)

#
# Gadget definitions.
#

START_COLLECTION("misc")

# Call a C language helper function by address.
simple("call",
    # Get our C runtime function's location as a pointer-sized immediate...
    "ldr x27, [x28], #8",

    # Store our TB return address for our helper.
    "str x28, [x25]",

    # Prepare ourselves to call into our C runtime...
    *C_CALL_PROLOGUE,

    # ... perform the call itself ...
    "blr x27",

    # Save the result of our call for later.
    "mov x27, x0",

    # ... and restore our environment.
    *C_CALL_EPILOGUE,

    # Restore our return value.
    "mov x0, x27"
)

# A call whose first N+1 arguments are env plus constants -- the pointer
# arguments of the SSE helpers above all -- computing them itself instead of
# after a mov and an addi gadget each: the stream holds the function, then
# the offsets for x0..xN. See tcg_out_call().
for n in range(8):
    simple(f"call_env{n}",
        "ldr x27, [x28], #8",
        *[line for i in range(n + 1)
              for line in ("ldr x26, [x28], #8", f"add x{i}, x14, x26")],
        "str x28, [x25]",
        *C_CALL_PROLOGUE,
        "blr x27",
        "mov x27, x0",
        *C_CALL_EPILOGUE,
        "mov x0, x27"
    )

# The inline float fast path (tcg/tcg-inline-fp.h): a registered SSE float
# helper's operation done here on NEON, under the conditions that make it
# exactly the helper's, and the call otherwise. The "_env" forms compute the
# arguments from env plus offsets, as call_envN does; the others find them
# in x0-x3 already. The stream holds the function, [the four offsets,] the
# float_status word's offset, then its mask (low half) and wanted value
# (high half). See tcg_out_call().
INLINE_FP_OPS = ("add", "sub", "mul", "div", "min", "max")
INLINE_FP_FORMS = (         # name, double, bytes (0: scalar)
    ("ps16", False, 16), ("ps32", False, 32), ("pd16", True, 16),
    ("pd32", True, 32), ("ss", False, 0), ("sd", True, 0),
)

def inline_fp(op, form, dbl, size, env):
    t = "2d" if dbl else "4s"
    p = "d" if dbl else "s"
    minmax = op in ("min", "max")
    lines = ["ldr x27, [x28], #8"]
    if env:
        for i in range(4):
            lines += ["ldr x26, [x28], #8", f"add x{i}, x14, x26"]
    lines += ["ldp x24, x26, [x28], #16"]

    # Rounding to nearest, no flushing, inexact already raised.
    if not minmax:
        lines += ["ldr w16, [x14, x24]", "and w16, w16, w26", "lsr x17, x26, #32",
                  "cmp w16, w17", "b.ne 9f"]

    # The smallest normal and infinity; v18 stays all ones while all is well.
    if dbl:
        lines += ["movz x16, #0x0010, lsl #48", "dup v16.2d, x16",
                  "movz x16, #0x7ff0, lsl #48", "dup v17.2d, x16"]
    else:
        lines += ["movz w16, #0x0080, lsl #16", "dup v16.4s, w16",
                  "movz w16, #0x7f80, lsl #16", "dup v17.4s, w16"]
    lines += ["movi v18.2d, #0xffffffffffffffff"]

    def normal(x):
        return [f"facge v19.{t}, v{x}.{t}, v16.{t}", f"facgt v20.{t}, v17.{t}, v{x}.{t}",
                "and v19.16b, v19.16b, v20.16b", f"fcmeq v20.{t}, v{x}.{t}, #0.0",
                "orr v19.16b, v19.16b, v20.16b", "and v18.16b, v18.16b, v19.16b"]

    def underflow(r, *nonzero):
        out = [f"fcmeq v19.{t}, v{r}.{t}, #0.0"]
        for x in nonzero:
            out += [f"fcmeq v20.{t}, v{x}.{t}, #0.0", "bic v19.16b, v19.16b, v20.16b"]
        return out + ["bic v18.16b, v18.16b, v19.16b"]

    for k in range(2 if size == 32 else 1):
        a, b, r = 3 * k, 3 * k + 1, 3 * k + 2
        if size == 0:
            lines += [f"ldr {p}{a}, [x2]", f"ldr {p}{b}, [x3]"]
        else:
            lines += [f"ldr q{a}, [x2, #{16 * k}]", f"ldr q{b}, [x3, #{16 * k}]"]
        if minmax:
            # x86's min is v < s ? v : s, max v > s ? v : s.
            x, y = (b, a) if op == "min" else (a, b)
            lines += [f"fcmgt v{r}.{t}, v{x}.{t}, v{y}.{t}", f"bsl v{r}.16b, v{a}.16b, v{b}.16b"]
        elif size == 0:
            lines += [f"f{op} {p}{r}, {p}{a}, {p}{b}"]
        else:
            lines += [f"f{op} v{r}.{t}, v{a}.{t}, v{b}.{t}"]
        # A scalar load or op zeroes the lanes above, which pass.
        lines += normal(a) + normal(b) + ([] if minmax else normal(r))
        if op == "mul":
            lines += underflow(r, a, b)
        elif op == "div":
            lines += underflow(r, a)

    lines += ["uminv s19, v18.4s", "fmov w16, s19", "cmn w16, #1", "b.ne 9f"]
    if size == 0:
        lines += ["ldr q6, [x2]", f"mov v6.{p}[0], v2.{p}[0]", "str q6, [x1]"]
    else:
        lines += [f"str q{3 * k + 2}, [x1, #{16 * k}]" for k in range(2 if size == 32 else 1)]
    lines += [*EPILOGUE, "9:",
              "str x28, [x25]", *C_CALL_PROLOGUE, "blr x27", "mov x27, x0",
              *C_CALL_EPILOGUE, "mov x0, x27"]

    simple(f"inline_fp{'_env' if env else ''}_{op}_{form}", *lines)

for env in (False, True):
    for op in INLINE_FP_OPS:
        for form, dbl, size in INLINE_FP_FORMS:
            inline_fp(op, form, dbl, size, env)

# Branch to a given immediate address.
simple("br",
    # Use our immediate argument as our new bytecode-pointer location.
    "ldr x28, [x28]"
)

# A goto_tb right after an addi_env, as nearly every TB leaves: the guest pc
# moved on by a constant, then the branch to the next TB, in one gadget.
# Every register is dead at a goto_tb, so it needs no register variants. The
# stream holds addi_env's offset and immediate, then br's target, which
# tb_target_set_jmp_target() patches. See tcg_out_goto_tb().
simple("addi_env_br",
    "ldp x26, x27, [x28], #16",
    "ldr x24, [x14, x26]",
    "add x24, x24, x27",
    "str x24, [x14, x26]",
    "ldr x28, [x28]"
)

# goto_ptr: continue with the gadget stream whose address is in a register --
# the next TB's, as helper_lookup_tb_ptr() found it, or the epilogue stream
# that tcg_target_qemu_prologue() emits for when it found none.
with_d("goto_ptr", "mov x28, Xd")


# The exit check at the start of every TB: a 32-bit load from env into Wd
# and a branch if it is negative, as one gadget instead of a load and a
# brcondi. The stream holds the env offset, then the branch target.
with_d("tb_exit_check",
    "ldp x26, x27, [x28], #16",
    "ldr Wd, [x14, x26]",
    "tst Wd, Wd",
    "csel x28, x27, x28, lt"
)

# Exit from a translation buffer execution.
simple("exit_tb",

    # We have a single immediate argument, which contains our return code.
    # Place it into x0, as one would a return code.
    "ldr x0, [x28], #8",

    # And finally, return back to the code that invoked our gadget stream.
    "ret"
)

# Memory barriers.
simple("mb_all", "dmb ish")
simple("mb_st",  "dmb ishst")
simple("mb_ld",  "dmb ishld")




for condition in ARCH_CONDITION_CODES:

    START_COLLECTION("setcond")

    # Performs a comparison between two operands.
    with_dnm(f"setcond_i32_{condition}",
        "subs Wd, Wn, Wm",
        f"cset Wd, {condition}"
    )
    with_dnm(f"setcond_i64_{condition}",
        "subs Xd, Xn, Xm",
        f"cset Xd, {condition}"
    )

    #
    # NOTE: we use _dnm for the conditional branches, even though we don't
    # actually do anything different based on the d argument. This gemerates
    # effectively 16 identical `brcond` gadgets for each condition; which we
    # use in the backend to spread out the actual branch sources we use.
    #
    # This is a slight mercy for the branch predictor, as not every conditional
    # branch is funneled throught the same address.
    #

    START_COLLECTION("brcond")

    # Branches iff a given comparison is true.
    with_dnm(f'brcond_i32_{condition}',

        # Grab our immediate argument.
        "ldr x27, [x28], #8",

        # Perform our comparison...
        "subs wzr, Wn, Wm",

        # ... and our conditional branch, which selectively sets w28 (our "gadget pointer")
        # to the new location, if required.
        f"csel x28, x27, x28, {condition}"
    )

    # Branches iff a given comparison is true.
    with_dnm(f'brcond_i64_{condition}',

        # Grab our immediate argument.
        "ldr x27, [x28], #8",

        # Perform our comparison and conditional branch.
        "subs xzr, Xn, Xm",

        # ... and our conditional branch, which selectively sets w28 (our "gadget pointer")
        # to the new location, if required.
        f"csel x28, x27, x28, {condition}"
    )

    # The same against a constant from the stream, which precedes the
    # branch target: comparisons with zero are common, and each TB starts
    # with one. d is unused, as for brcond: it spreads the branch sources.
    with_dn(f'brcondi_i32_{condition}',
        "ldr x26, [x28], #8",
        "ldr x27, [x28], #8",
        "subs wzr, Wn, w26",
        f"csel x28, x27, x28, {condition}"
    )
    with_dn(f'brcondi_i64_{condition}',
        "ldr x26, [x28], #8",
        "ldr x27, [x28], #8",
        "subs xzr, Xn, x26",
        f"csel x28, x27, x28, {condition}"
    )


START_COLLECTION("mov")


# MOV variants.
with_dn("mov_i32",     "mov Wd, Wn")
with_dn("mov_i64",     "mov Xd, Xn")
with_d("movi_i32", "ldr Wd, [x28], #8")
with_d("movi_i64", "ldr Xd, [x28], #8")

# Create MOV variants that have common constants built in to the gadget.
# This optimization helps costly reads from memories for simple operations.
with_d_immediate("movi_imm_i32", "mov Wd, #Ii", immediate_range=range(64))
with_d_immediate("movi_imm_i64", "mov Xd, #Ii", immediate_range=range(64))

START_COLLECTION("load_unsigned")

# LOAD variants.
# TODO: should the signed variants have X variants for _i64?
ldst_dn("ld8u",      "ldrb  Wd, [Xn, x27]")
ldst_dn("ld16u",     "ldrh  Wd, [Xn, x27]")
ldst_dn("ld32u",     "ldr   Wd, [Xn, x27]")
ldst_dn("ld_i64",    "ldr   Xd, [Xn, x27]")

START_COLLECTION("load_signed")

ldst_dn("ld8s_i32",  "ldrsb Wd, [Xn, x27]")
ldst_dn("ld8s_i64",  "ldrsb Xd, [Xn, x27]")
ldst_dn("ld16s_i32", "ldrsh Wd, [Xn, x27]")
ldst_dn("ld16s_i64", "ldrsh Xd, [Xn, x27]")
ldst_dn("ld32s_i64", "ldrsw Xd, [Xn, x27]")

START_COLLECTION("store")

# Two 64-bit env slots side by side, as one gadget: the guest registers sit
# next to each other in env, so a TB's syncs and reloads of them come in
# runs, and so do the halves of a 128-bit value moved to or from an XMM
# register. The stream holds the offset of the lower slot, Xd's; Xm's is 8
# above it. See tcg_out_ld() and tcg_out_st(). The loads are two LDRs, as
# an LDP of one register to both is unpredictable.
with_pair("stp_env", ('d', 'm'), "ldr x27, [x28], #8", "add x27, x14, x27", "stp Xd, Xm, [x27]")
with_pair("ldp_env", ('d', 'm'), "ldr x27, [x28], #8", "add x27, x14, x27", "ldr Xd, [x27]", "ldr Xm, [x27, #8]")

# A 64-bit env slot updated by an add or and of an immediate, as one gadget
# for the load, the op and the store: Xn = the slot, Xd = Xn op imm, Xd back
# to the slot. Above all this is the guest pc, which a TB moves on by a
# constant before leaving to another page. The stream holds the offset, then
# the immediate. See tcg_out_st().
for op in ("add", "and"):
    with_pair(f"{op}i_env", ('d', 'n'), "ldp x26, x27, [x28], #16", "ldr Xn, [x14, x26]",
              f"{op} Xd, Xn, x27", "str Xd, [x14, x26]")

# A constant stored to an env slot: above all x86's cc_op, set as a TB
# leaves. sti32_env's one stream word holds the constant in its low half and
# the (signed) offset in its high half; sti64_env's stream holds the offset,
# then the constant. See tcg_out_sti(). movi_st32_env is the same for a
# constant that also stays in Xd, joining the movi and the store; see
# tcg_out_st().
simple("sti32_env", "ldr x27, [x28], #8", "asr x26, x27, #32", "str w27, [x14, x26]")
simple("sti64_env", "ldp x26, x27, [x28], #16", "str x27, [x14, x26]")
with_d("movi_st32_env", "ldr x27, [x28], #8", "asr x26, x27, #32", "mov Wd, w27",
       "str Wd, [x14, x26]")

# STORE variants.
ldst_dn("st8",         "strb  Wd, [Xn, x27]")
ldst_dn("st16",        "strh  Wd, [Xn, x27]")
ldst_dn("st_i32",      "str   Wd, [Xn, x27]")
ldst_dn("st_i64",      "str   Xd, [Xn, x27]")

# QEMU LD/ST are handled in our C runtime rather than with simple gadgets,
# as they're nontrivial.

START_COLLECTION("arithmetic")

# Trivial arithmetic.
math_dnm("add" , "add" )
math_dni("addi", "add" )
math_dnm("sub" , "sub" )
math_dnm("mul" , "mul" )
math_dnm("div" , "sdiv")
math_dnm("divu", "udiv")

# Division remainder
with_dnm("rem_i32",  "sdiv w27, Wn, Wm", "msub Wd, w27, Wm, Wn")
with_dnm("rem_i64",  "sdiv x27, Xn, Xm", "msub Xd, x27, Xm, Xn")
with_dnm("remu_i32", "udiv w27, Wn, Wm", "msub Wd, w27, Wm, Wn")
with_dnm("remu_i64", "udiv x27, Xn, Xm", "msub Xd, x27, Xm, Xn")

START_COLLECTION("logical")

# Trivial logical.
math_dn( "not",  "mvn")
math_dn( "neg",  "neg")
math_dnm("and",  "and")
math_dnm("andc", "bic")
math_dnm("or",   "orr")
math_dnm("orc",  "orn")
math_dnm("xor",  "eor")
math_dnm("eqv",  "eon")
math_dnm("shl",  "lsl")
math_dnm("shr",  "lsr")
math_dnm("sar",  "asr")
math_dnm("rotr", "ror")

# The same with an immediate; sub has none, as TCG turns a subtraction of a
# constant into an addition.
math_dni("andi", "and")
math_dni("ori",  "orr")
math_dni("xori", "eor")
math_dni("shli", "lsl")
math_dni("shri", "lsr")
math_dni("sari", "asr")

# AArch64 lacks a Rotate Left; so we instead rotate right by a negative.
with_dnm("rotl_i32", "neg w27, Wm", "ror Wd, Wn, w27")
with_dnm("rotl_i64", "neg w27, Wm", "ror Xd, Xn, x27")

# We'll synthesize several instructions that don't exist; since it's still faster
# to run these as gadgets.
with_dnm("nand_i32", "and Wd, Wn, Wm", "mvn Wd, Wd")
with_dnm("nand_i64", "and Xd, Xn, Xm", "mvn Xd, Xd")
with_dnm("nor_i32",  "orr Wd, Wn, Wm", "mvn Wd, Wd")
with_dnm("nor_i64",  "orr Xd, Xn, Xm", "mvn Xd, Xd")

START_COLLECTION("bitwise")

# Count leading zeroes, with a twist: QEMU requires us to provide
# a default value for when the argument is 0.
with_dnm("clz_i32",

    # Perform the core CLZ into w26.
    "clz w26, Wn",

    # Check Wn to see if it was zero
    "tst Wn, Wn",

    # If it was zero, accept the argument provided in Wm.
    # Otherwise, accept our result from w26.
    "csel Wd, Wm, w26, eq"
)
with_dnm("clz_i64",

    # Perform the core CLZ into w26.
    "clz x26, Xn",

    # Check Wn to see if it was zero
    "tst Xn, Xn",

    # If it was zero, accept the argument provided in Wm.
    # Otherwise, accept our result from w26.
    "csel Xd, Xm, x26, eq"
)


# Count trailing zeroes, with a twist: QEMU requires us to provide
# a default value for when the argument is 0.
with_dnm("ctz_i32",
    # Reverse our bits before performing our actual clz.
    "rbit w26, Wn",
    "clz w26, w26",

    # Check Wn to see if it was zero
    "tst Wn, Wn",

    # If it was zero, accept the argument provided in Wm.
    # Otherwise, accept our result from w26.
    "csel Wd, Wm, w26, eq"
)
with_dnm("ctz_i64",

    # Perform the core CLZ into w26.
    "rbit x26, Xn",
    "clz x26, x26",

    # Check Wn to see if it was zero
    "tst Xn, Xn",

    # If it was zero, accept the argument provided in Wm.
    # Otherwise, accept our result from w26.
    "csel Xd, Xm, x26, eq"
)


START_COLLECTION("extension")

# Numeric extension.
math_dn("ext8s",      "sxtb", source_is_wn=True)
with_dn("ext8u",      "and Xd, Xn, #0xff")
math_dn("ext16s",     "sxth", source_is_wn=True)
with_dn("ext16u",     "and Wd, Wn, #0xffff")
with_dn("ext32s_i64", "sxtw Xd, Wn")
with_dn("ext32u_i64", "mov Wd, Wn")

# Numeric extraction.
with_dn("extrl",      "mov Wd, Wn")
with_dn("extrh",      "lsr Xd, Xn, #32")

START_COLLECTION("byteswap")

# Byte swapping.
with_dn("bswap16",    "rev w27, Wn", "lsr Wd, w27, #16")
with_dn("bswap32",    "rev Wd, Wn")
with_dn("bswap64",    "rev Xd, Xn")


# Handlers for QEMU_LD, which handles guest <- host loads. Each comes plain,
# and ordered ("_ord": LDAPR, for guests such as x86 whose memory order TCG
# would otherwise keep with a barrier gadget before every access; see
# tcg_ldst_ordered()). LDAPR has no register offset, so the ordered gadgets
# add the TLB addend to the address first, and zero-extends, so the signed
# ones extend afterwards.
LD_OPS = (
    # name, helper, size, plain 32-bit, plain 64-bit, ordered 32-bit, ordered 64-bit
    ("ub",   "helper_ldub_mmu", 1, ["ldrb Wd, [Xn, x27]"],  ["ldrb Wd, [Xn, x27]"],
                                   ["ldaprb Wd, [x27]"],    ["ldaprb Wd, [x27]"]),
    ("leuw", "helper_lduw_mmu", 2, ["ldrh Wd, [Xn, x27]"],  ["ldrh Wd, [Xn, x27]"],
                                   ["ldaprh Wd, [x27]"],    ["ldaprh Wd, [x27]"]),
    ("leul", "helper_ldul_mmu", 4, ["ldr Wd, [Xn, x27]"],   ["ldr Wd, [Xn, x27]"],
                                   ["ldapr Wd, [x27]"],     ["ldapr Wd, [x27]"]),
    ("leq",  "helper_ldq_mmu",  8, ["ldr Xd, [Xn, x27]"],   ["ldr Xd, [Xn, x27]"],
                                   ["ldapr Xd, [x27]"],     ["ldapr Xd, [x27]"]),
    ("sb",   "helper_ldsb_mmu", 1, ["ldrsb Wd, [Xn, x27]"], ["ldrsb Xd, [Xn, x27]"],
                                   ["ldaprb Wd, [x27]", "sxtb Wd, Wd"], ["ldaprb Wd, [x27]", "sxtb Xd, Wd"]),
    ("lesw", "helper_ldsw_mmu", 2, ["ldrsh Wd, [Xn, x27]"], ["ldrsh Xd, [Xn, x27]"],
                                   ["ldaprh Wd, [x27]", "sxth Wd, Wd"], ["ldaprh Wd, [x27]", "sxth Xd, Wd"]),
    ("lesl", "helper_ldsl_mmu", 4, ["ldrsw Xd, [Xn, x27]"], ["ldrsw Xd, [Xn, x27]"],
                                   ["ldapr Wd, [x27]", "sxtw Xd, Wd"], ["ldapr Wd, [x27]", "sxtw Xd, Wd"]),
)

for ordered in (False, True):
    for subtype in ('aligned', 'unaligned', 'slowpath'):
        is_aligned  = (subtype == 'aligned')
        is_slowpath = (subtype == 'slowpath')
        variant = subtype + ("_ord" if ordered else "")

        for signedness, ops in (("unsigned", LD_OPS[:4]), ("signed", LD_OPS[4:])):
            START_COLLECTION(f"qemu_ld_{variant}_{signedness}_le", needs_defs=not is_slowpath)
            for op, helper, size, plain32, plain64, ord32, ord64 in ops:
                ld_thunk(f"qemu_ld_{op}_{variant}", is_aligned=is_aligned, slowpath_helper=helper,
                    fastpath_32b=ord32 if ordered else plain32,
                    fastpath_64b=ord64 if ordered else plain64,
                    force_slowpath=is_slowpath, ordered=size if ordered else None,
                )


# Handlers for QEMU_ST, which handles guest -> host stores; plain and ordered
# (STLR) as for the loads.
ST_OPS = (
    ("ub",   "helper_stb_mmu", 1, "strb Wd, [Xn, x27]", "stlrb Wd, [x27]", "stlrb Wd, [x27]"),
    ("leuw", "helper_stw_mmu", 2, "strh Wd, [Xn, x27]", "stlrh Wd, [x27]", "stlrh Wd, [x27]"),
    ("leul", "helper_stl_mmu", 4, "str Wd, [Xn, x27]",  "stlr Wd, [x27]",  "stlr Wd, [x27]"),
    ("leq",  "helper_stq_mmu", 8, "str Xd, [Xn, x27]",  "stlr Xd, [x27]",  "stlr Xd, [x27]"),
)

for ordered in (False, True):
    for subtype in ('aligned', 'unaligned', 'slowpath'):
        is_aligned  = (subtype == 'aligned')
        is_slowpath = (subtype == 'slowpath')
        variant = subtype + ("_ord" if ordered else "")

        START_COLLECTION(f"qemu_st_{variant}_le", needs_defs=not is_slowpath)
        for op, helper, size, plain, ord32, ord64 in ST_OPS:
            st_thunk(f"qemu_st_{op}_{variant}", is_aligned=is_aligned, slowpath_helper=helper,
                fastpath_32b=[ord32] if ordered else [plain],
                fastpath_64b=[ord64] if ordered else [plain],
                force_slowpath=is_slowpath, ordered=size if ordered else None,
            )


# Handlers for QEMU_LD2/ST2 with 128-bit accesses (x86's SSE/AVX loads and
# stores), as one LDP/STP instead of two 64-bit accesses and the address
# arithmetic between them. The data registers are fixed -- R0/R1 for loads,
# R2/R3 for stores -- which keeps the gadget count down (one per address
# register), and is exactly where helper_ld16_mmu() returns its Int128 and
# helper_st16_mmu() takes it. The fast path requires LSE2 for LDP/STP to be
# single-copy atomic; TCG_TARGET_HAS_qemu_ldst_i128 says so. An alignment
# the gadget does not check (align=0 or a larger one) goes to the slow path,
# which checks it and raises the fault.
#
# The ordered ("_ord") gadgets are for tcg_ldst_ordered(). Without FEAT_LRCPC3
# there is no ordered LDP/STP, so a barrier after the load, or before the
# store, gives the order an LDAPR or STLR would.
START_COLLECTION("qemu_ldst_i128", needs_defs=True)

def ldst_i128(is_ld, align, mmu_idx, ordered):
    op = "ld" if is_ld else "st"
    suffix = "any" if mmu_idx is None else f"idx{mmu_idx}"
    ld_barrier = ["dmb ishld"] if ordered and is_ld else []
    st_barrier = ["dmb ishst"] if ordered and not is_ld else []
    fast = []
    if mmu_idx is not None:
        fast = [
            *create_tlb_fastpath(is_aligned=False, is_write=not is_ld, size=16),
            *([f"tst Xn, #{align - 1}", "b.ne 0f"] if align else []),
            "add x27, x27, Xn",
            *st_barrier,
            "ldp x0, x1, [x27]" if is_ld else "stp x2, x3, [x27]",
            *ld_barrier,
            "add x28, x28, #8",
            *EPILOGUE,
        ]
    if is_ld:
        slow = [
            "mov x27, Xn",
            *C_CALL_PROLOGUE,
            "mov   x0, x14",
            "mov   x1, x27",
            "ldr   x2, [x28], #8",
            "mov   x3, x28",
            "bl _helper_ld16_mmu",
            *C_CALL_EPILOGUE,
            *ld_barrier,
        ]
    else:
        slow = [
            "mov x26, Xn",
            *C_CALL_PROLOGUE,
            "mov   x0, x14",
            "mov   x1, x26",
            "ldr   x4, [x28], #8",
            "mov   x5, x28",
            *st_barrier,
            "bl _helper_st16_mmu",
            *C_CALL_EPILOGUE,
        ]
    variant = "i128_ord" if ordered else "i128"
    with_single(f"qemu_{op}_{variant}_a{align}_{suffix}", "n", *fast, "0:", *slow,
                "add x28, x28, #8",
                operands=None if mmu_idx is None else tlb_operands(mmu_idx))

for ordered in (False, True):
    for is_ld in (True, False):
        for align in (0, 16, 32):
            for mmu_idx in QEMU_TLB_FAST_MMU_INDICES:
                ldst_i128(is_ld, align, mmu_idx, ordered)
        ldst_i128(is_ld, 0, None, ordered)


#
# SIMD/Vector ops
#

# SIMD MOVI instructions.
START_COLLECTION(f"simd_base")

# Unoptimized/unoptimizable load of a vector64; grabbing an immediate.
with_d("ldi_d", "ldr Dd, [x28], #8")
with_d("ldi_q", "ldr Qd, [x28], #16")

# General purpose reg -> vec rec loads
vector_dn("dup", "dup Vd.S, Wn")

# move vector -> GP reg
with_dn("umov_s0", "umov Wd, Vn.s[0]")
with_dn("umov_d0", "umov Xd, Vn.d[0]")

# mov GP reg -> vector
with_dn("ins_s0", "ins Vd.s[0], Wn")
with_dn("ins_d0", "ins Vd.d[0], Xn")


# Memory -> vec reg loads.
# The offset of the load is stored in a 64b immediate.

# Duplicating load.
# TODO: possibly squish the add into the ld1r, if that's valid?
vector_dn("dupm", "ldr x27, [x28], #8", "add x27, x27, Xn", "ld1r {Vd.S}, [x27]")

# Direct loads.
with_dn("ldr_d",  "ldr x27, [x28], #8", "ldr Dd, [Xn, x27]")
with_dn("ldr_q",  "ldr x27, [x28], #8", "ldr Qd, [Xn, x27]")

# vec -> reg stores.
# The offset of the stores is stored in a 64b immediate.
with_dn("str_d",  "ldr x27, [x28], #8", "str Dd, [Xn, x27]")
with_dn("str_q",  "ldr x27, [x28], #8", "str Qd, [Xn, x27]")

# Sixteen zero bytes stored to env, as x86 clears the upper half of a YMM
# register after each VEX-encoded SSE op: one gadget for the MOVI of zero
# and the STR that would store it. The stream holds the offset. See
# tcg_out_vec_op().
simple("st_zero_q_env", "ldr x27, [x28], #8", "add x27, x14, x27", "stp xzr, xzr, [x27]")


START_COLLECTION(f"simd_arithmetic")

vector_math_dnm("add",   "add")
vector_math_dnm("usadd", "uqadd")
vector_math_dnm("ssadd", "sqadd")
vector_math_dnm("sub",   "sub")
vector_math_dnm("ussub", "uqsub")
vector_math_dnm("sssub", "sqsub")
vector_math_dnm_no64("mul",  "mul")
vector_math_dnm_no64("smax", "smax")
vector_math_dnm_no64("smin", "smin")
vector_math_dnm_no64("umax", "umax")
vector_math_dnm_no64("umin", "umin")

START_COLLECTION(f"simd_logical")

vector_logic_dnm("and",  "and")
vector_logic_dnm("andc", "bic")
vector_logic_dnm("or",   "orr")
vector_logic_dnm("orc",  "orn")
vector_logic_dnm("xor",  "eor")
vector_logic_dn( "not",  "not")
vector_dn("neg", "neg Vd.S, Vn.S")
vector_dn("abs", "abs Vd.S, Vn.S")
vector_logic_dnm( "bit",  "bit")
vector_logic_dnm( "bif",  "bif")
vector_logic_dnm( "bsl",  "bsl")

vector_math_dnm("shlv", "ushl")
vector_math_dnm("sshl", "sshl")

def filter_shl(size, imm):
    match size:
        case '16b': return imm >= 8
        case '8b': return imm >= 8
        case '4h': return imm >= 16
        case '8h': return imm >= 16
        case '2s': return imm >= 32
        case '4s': return imm >= 32
    return False

def filter_shr(size, imm):
    if imm == 0:
        return True
    match size:
        case '16b': return imm > 8
        case '8b': return imm > 8
        case '4h': return imm > 16
        case '8h': return imm > 16
        case '2s': return imm > 32
        case '4s': return imm > 32
    return False

vector_math_dn_immediate("shl", "shl", immediate_range=range(64), filter=filter_shl)
vector_math_dn_immediate("ushr", "ushr", immediate_range=range(1,65), filter=filter_shr)
vector_math_dn_immediate("sshr", "sshr", immediate_range=range(1,65), filter=filter_shr)
vector_math_dn_immediate("sli", "sli", immediate_range=range(64), filter=filter_shl)

vector_dnm("cmeq", "cmeq Vd.S, Vn.S, Vm.S", scalar="cmeq Dd, Dn, Dm")
vector_dnm("cmgt", "cmgt Vd.S, Vn.S, Vm.S", scalar="cmgt Dd, Dn, Dm")
vector_dnm("cmge", "cmge Vd.S, Vn.S, Vm.S", scalar="cmge Dd, Dn, Dm")
vector_dnm("cmhi", "cmhi Vd.S, Vn.S, Vm.S", scalar="cmhi Dd, Dn, Dm")
vector_dnm("cmhs", "cmhs Vd.S, Vn.S, Vm.S", scalar="cmhs Dd, Dn, Dm")

START_COLLECTION(f"simd_immediate")

# Simple imm8 movs...
with_d_immediate("movi_cmode_e_op0_q0",  "movi Vd.8b, #Ii",          immediate_range=range(256))
with_d_immediate("movi_cmode_e_op0_q1",  "movi Vd.16b, #Ii",         immediate_range=range(256))

# ... all 00/FF movs...
with_d_immediate("movi_cmode_e_op1_q0",  "movi Dd, #Si",             immediate_range=range(256))
with_d_immediate("movi_cmode_e_op1_q1",  "movi Vd.2d, #Si",          immediate_range=range(256))

# Halfword MOVs.
with_d_immediate("movi_cmode_8_op0_q0",  "movi Vd.4h, #Ii",         immediate_range=range(256))
with_d_immediate("movi_cmode_8_op0_q1",  "movi Vd.8h, #Ii",         immediate_range=range(256))
with_d_immediate("mvni_cmode_8_op0_q0",  "mvni Vd.4h, #Ii",         immediate_range=range(256))
with_d_immediate("mvni_cmode_8_op0_q1",  "mvni Vd.8h, #Ii",         immediate_range=range(256))
with_d_immediate("movi_cmode_a_op0_q0",  "movi Vd.4h, #Ii, lsl #8", immediate_range=range(256))
with_d_immediate("movi_cmode_a_op0_q1",  "movi Vd.8h, #Ii, lsl #8", immediate_range=range(256))
with_d_immediate("mvni_cmode_a_op0_q0",  "mvni Vd.4h, #Ii, lsl #8", immediate_range=range(256))
with_d_immediate("mvni_cmode_a_op0_q1",  "mvni Vd.8h, #Ii, lsl #8", immediate_range=range(256))

# Halfword ORIs, for building complex MOVs.
with_d_immediate("orr_cmode_a_op0_q0",   "orr Vd.4h, #Ii, lsl #8",  immediate_range=range(256))
with_d_immediate("orr_cmode_a_op0_q1",   "orr Vd.8h, #Ii, lsl #8",  immediate_range=range(256))


START_COLLECTION("movcond")

# Comparisons that only set the flags, for the gadget that follows to consume.
# The dispatch between gadgets (a load and an indirect branch) leaves NZCV
# alone, which is what lets movcond and negsetcond be two gadgets rather than
# one per combination of five registers.
with_nm("cmp_i32", "cmp Wn, Wm")
with_nm("cmp_i64", "cmp Xn, Xm")

for condition in ARCH_CONDITION_CODES:
    # movcond's second half. Always the X form: the high half of an I32
    # result is don't-care, and every TCTI consumer of one reads the W form.
    with_dnm(f"csel_{condition}", f"csel Xd, Xn, Xm, {condition}")

    # negsetcond's second half.
    with_d(f"csetm_i32_{condition}", f"csetm Wd, {condition}")
    with_d(f"csetm_i64_{condition}", f"csetm Xd, {condition}")



# Print a list of output files generated.
output_c_filenames = (f"'tcti_{name}_gadgets.c'" for name in output_files.keys())
output_h_filenames = (f"'tcti_{name}_gadgets.h'" for name in output_files.keys())

print("Sources generated:",    file=sys.stderr)
print(f"gadgets = [",          file=sys.stderr)
print("      tcti_gadgets.h,", file=sys.stderr)

for name in output_files.keys():
    print(f"      'tcti_{name}_gadgets.c',", file=sys.stderr)
    print(f"      'tcti_{name}_gadgets.h',", file=sys.stderr)

print(f"]", file=sys.stderr)

# Statistics.
sys.stderr.write(f"\nGenerated {gadgets} gadgets with {instructions} instructions (~{(instructions * 4) // 1024 // 1024} MiB).\n\n")
