/* SPDX-License-Identifier: GPL-2.0-or-later */
/*
 * Renames for the AArch64 hybrid's inactive backend: every file-scope name
 * that both aarch64 and TCTI define, and the two each defines that tcg.c
 * defines for the other (tcg_qemu_tb_exec, tcg_register_jit). Each becomes
 * <TCG_HYBRID_PREFIX>_<name>, the prefix being whatever is defined where the
 * name is used: tcg-target.c.inc defines it around the backend it includes.
 * tcg-hybrid-unrename.h undoes this.
 *
 * Listed from the two backends' top-level declarations (clang -ast-dump=json
 * of tcg.c, preprocessed for each). A name both come to define and this does
 * not list fails to compile as a redefinition, so the list cannot go stale
 * silently; one that is no longer needed costs nothing.
 */

#define TCG_HYBRID_GLUE2(p, n)  p##_##n
#define TCG_HYBRID_GLUE(p, n)   TCG_HYBRID_GLUE2(p, n)
#define TCG_HYBRID_NAME(n)      TCG_HYBRID_GLUE(TCG_HYBRID_PREFIX, n)

#define is_shimm16                  TCG_HYBRID_NAME(is_shimm16)
#define outop_add                   TCG_HYBRID_NAME(outop_add)
#define outop_addci                 TCG_HYBRID_NAME(outop_addci)
#define outop_addcio                TCG_HYBRID_NAME(outop_addcio)
#define outop_addco                 TCG_HYBRID_NAME(outop_addco)
#define outop_and                   TCG_HYBRID_NAME(outop_and)
#define outop_andc                  TCG_HYBRID_NAME(outop_andc)
#define outop_brcond                TCG_HYBRID_NAME(outop_brcond)
#define outop_bswap16               TCG_HYBRID_NAME(outop_bswap16)
#define outop_bswap32               TCG_HYBRID_NAME(outop_bswap32)
#define outop_bswap64               TCG_HYBRID_NAME(outop_bswap64)
#define outop_clz                   TCG_HYBRID_NAME(outop_clz)
#define outop_ctpop                 TCG_HYBRID_NAME(outop_ctpop)
#define outop_ctz                   TCG_HYBRID_NAME(outop_ctz)
#define outop_deposit               TCG_HYBRID_NAME(outop_deposit)
#define outop_divs                  TCG_HYBRID_NAME(outop_divs)
#define outop_divs2                 TCG_HYBRID_NAME(outop_divs2)
#define outop_divu                  TCG_HYBRID_NAME(outop_divu)
#define outop_divu2                 TCG_HYBRID_NAME(outop_divu2)
#define outop_eqv                   TCG_HYBRID_NAME(outop_eqv)
#define outop_extract               TCG_HYBRID_NAME(outop_extract)
#define outop_extract2              TCG_HYBRID_NAME(outop_extract2)
#define outop_extrh_i64_i32         TCG_HYBRID_NAME(outop_extrh_i64_i32)
#define outop_ld16s                 TCG_HYBRID_NAME(outop_ld16s)
#define outop_ld16u                 TCG_HYBRID_NAME(outop_ld16u)
#define outop_ld32s                 TCG_HYBRID_NAME(outop_ld32s)
#define outop_ld32u                 TCG_HYBRID_NAME(outop_ld32u)
#define outop_ld8s                  TCG_HYBRID_NAME(outop_ld8s)
#define outop_ld8u                  TCG_HYBRID_NAME(outop_ld8u)
#define outop_movcond               TCG_HYBRID_NAME(outop_movcond)
#define outop_mul                   TCG_HYBRID_NAME(outop_mul)
#define outop_muls2                 TCG_HYBRID_NAME(outop_muls2)
#define outop_mulsh                 TCG_HYBRID_NAME(outop_mulsh)
#define outop_mulu2                 TCG_HYBRID_NAME(outop_mulu2)
#define outop_muluh                 TCG_HYBRID_NAME(outop_muluh)
#define outop_nand                  TCG_HYBRID_NAME(outop_nand)
#define outop_neg                   TCG_HYBRID_NAME(outop_neg)
#define outop_negsetcond            TCG_HYBRID_NAME(outop_negsetcond)
#define outop_nor                   TCG_HYBRID_NAME(outop_nor)
#define outop_not                   TCG_HYBRID_NAME(outop_not)
#define outop_or                    TCG_HYBRID_NAME(outop_or)
#define outop_orc                   TCG_HYBRID_NAME(outop_orc)
#define outop_qemu_ld               TCG_HYBRID_NAME(outop_qemu_ld)
#define outop_qemu_ld2              TCG_HYBRID_NAME(outop_qemu_ld2)
#define outop_qemu_st               TCG_HYBRID_NAME(outop_qemu_st)
#define outop_qemu_st2              TCG_HYBRID_NAME(outop_qemu_st2)
#define outop_rems                  TCG_HYBRID_NAME(outop_rems)
#define outop_remu                  TCG_HYBRID_NAME(outop_remu)
#define outop_rotl                  TCG_HYBRID_NAME(outop_rotl)
#define outop_rotr                  TCG_HYBRID_NAME(outop_rotr)
#define outop_sar                   TCG_HYBRID_NAME(outop_sar)
#define outop_setcond               TCG_HYBRID_NAME(outop_setcond)
#define outop_sextract              TCG_HYBRID_NAME(outop_sextract)
#define outop_shl                   TCG_HYBRID_NAME(outop_shl)
#define outop_shr                   TCG_HYBRID_NAME(outop_shr)
#define outop_st                    TCG_HYBRID_NAME(outop_st)
#define outop_st16                  TCG_HYBRID_NAME(outop_st16)
#define outop_st8                   TCG_HYBRID_NAME(outop_st8)
#define outop_sub                   TCG_HYBRID_NAME(outop_sub)
#define outop_subbi                 TCG_HYBRID_NAME(outop_subbi)
#define outop_subbio                TCG_HYBRID_NAME(outop_subbio)
#define outop_subbo                 TCG_HYBRID_NAME(outop_subbo)
#define outop_xor                   TCG_HYBRID_NAME(outop_xor)
#define patch_reloc                 TCG_HYBRID_NAME(patch_reloc)
#define tb_target_set_jmp_target    TCG_HYBRID_NAME(tb_target_set_jmp_target)
#define tcg_can_emit_vec_op         TCG_HYBRID_NAME(tcg_can_emit_vec_op)
#define tcg_expand_vec_op           TCG_HYBRID_NAME(tcg_expand_vec_op)
#define tcg_out_addi_ptr            TCG_HYBRID_NAME(tcg_out_addi_ptr)
#define tcg_out_br                  TCG_HYBRID_NAME(tcg_out_br)
#define tcg_out_call                TCG_HYBRID_NAME(tcg_out_call)
#define tcg_out_dup_vec             TCG_HYBRID_NAME(tcg_out_dup_vec)
#define tcg_out_dupi_vec            TCG_HYBRID_NAME(tcg_out_dupi_vec)
#define tcg_out_dupm_vec            TCG_HYBRID_NAME(tcg_out_dupm_vec)
#define tcg_out_exit_tb             TCG_HYBRID_NAME(tcg_out_exit_tb)
#define tcg_out_ext16s              TCG_HYBRID_NAME(tcg_out_ext16s)
#define tcg_out_ext16u              TCG_HYBRID_NAME(tcg_out_ext16u)
#define tcg_out_ext32s              TCG_HYBRID_NAME(tcg_out_ext32s)
#define tcg_out_ext32u              TCG_HYBRID_NAME(tcg_out_ext32u)
#define tcg_out_ext8s               TCG_HYBRID_NAME(tcg_out_ext8s)
#define tcg_out_ext8u               TCG_HYBRID_NAME(tcg_out_ext8u)
#define tcg_out_extrl_i64_i32       TCG_HYBRID_NAME(tcg_out_extrl_i64_i32)
#define tcg_out_exts_i32_i64        TCG_HYBRID_NAME(tcg_out_exts_i32_i64)
#define tcg_out_extu_i32_i64        TCG_HYBRID_NAME(tcg_out_extu_i32_i64)
#define tcg_out_goto_ptr            TCG_HYBRID_NAME(tcg_out_goto_ptr)
#define tcg_out_goto_tb             TCG_HYBRID_NAME(tcg_out_goto_tb)
#define tcg_out_ld                  TCG_HYBRID_NAME(tcg_out_ld)
#define tcg_out_mb                  TCG_HYBRID_NAME(tcg_out_mb)
#define tcg_out_mov                 TCG_HYBRID_NAME(tcg_out_mov)
#define tcg_out_movi                TCG_HYBRID_NAME(tcg_out_movi)
#define tcg_out_movr                TCG_HYBRID_NAME(tcg_out_movr)
#define tcg_out_nop_fill            TCG_HYBRID_NAME(tcg_out_nop_fill)
#define tcg_out_qemu_ld_slow_path   TCG_HYBRID_NAME(tcg_out_qemu_ld_slow_path)
#define tcg_out_qemu_st_slow_path   TCG_HYBRID_NAME(tcg_out_qemu_st_slow_path)
#define tcg_out_set_borrow          TCG_HYBRID_NAME(tcg_out_set_borrow)
#define tcg_out_set_carry           TCG_HYBRID_NAME(tcg_out_set_carry)
#define tcg_out_st                  TCG_HYBRID_NAME(tcg_out_st)
#define tcg_out_sti                 TCG_HYBRID_NAME(tcg_out_sti)
#define tcg_out_tb_start            TCG_HYBRID_NAME(tcg_out_tb_start)
#define tcg_out_vec_op              TCG_HYBRID_NAME(tcg_out_vec_op)
#define tcg_out_xchg                TCG_HYBRID_NAME(tcg_out_xchg)
#define tcg_qemu_tb_exec            TCG_HYBRID_NAME(tcg_qemu_tb_exec)
#define tcg_register_jit            TCG_HYBRID_NAME(tcg_register_jit)
#define tcg_target_call_iarg_regs   TCG_HYBRID_NAME(tcg_target_call_iarg_regs)
#define tcg_target_call_oarg_reg    TCG_HYBRID_NAME(tcg_target_call_oarg_reg)
#define tcg_target_const_match      TCG_HYBRID_NAME(tcg_target_const_match)
#define tcg_target_has_memory_bswap TCG_HYBRID_NAME(tcg_target_has_memory_bswap)
#define tcg_target_init             TCG_HYBRID_NAME(tcg_target_init)
#define tcg_target_op_def           TCG_HYBRID_NAME(tcg_target_op_def)
#define tcg_target_qemu_prologue    TCG_HYBRID_NAME(tcg_target_qemu_prologue)
#define tcg_target_reg_alloc_order  TCG_HYBRID_NAME(tcg_target_reg_alloc_order)
#define tgen_add                    TCG_HYBRID_NAME(tgen_add)
#define tgen_addi                   TCG_HYBRID_NAME(tgen_addi)
#define tgen_and                    TCG_HYBRID_NAME(tgen_and)
#define tgen_andc                   TCG_HYBRID_NAME(tgen_andc)
#define tgen_andi                   TCG_HYBRID_NAME(tgen_andi)
#define tgen_brcond                 TCG_HYBRID_NAME(tgen_brcond)
#define tgen_brcondi                TCG_HYBRID_NAME(tgen_brcondi)
#define tgen_bswap16                TCG_HYBRID_NAME(tgen_bswap16)
#define tgen_bswap32                TCG_HYBRID_NAME(tgen_bswap32)
#define tgen_bswap64                TCG_HYBRID_NAME(tgen_bswap64)
#define tgen_clz                    TCG_HYBRID_NAME(tgen_clz)
#define tgen_ctz                    TCG_HYBRID_NAME(tgen_ctz)
#define tgen_divs                   TCG_HYBRID_NAME(tgen_divs)
#define tgen_divu                   TCG_HYBRID_NAME(tgen_divu)
#define tgen_eqv                    TCG_HYBRID_NAME(tgen_eqv)
#define tgen_extract                TCG_HYBRID_NAME(tgen_extract)
#define tgen_extrh_i64_i32          TCG_HYBRID_NAME(tgen_extrh_i64_i32)
#define tgen_ld16s                  TCG_HYBRID_NAME(tgen_ld16s)
#define tgen_ld16u                  TCG_HYBRID_NAME(tgen_ld16u)
#define tgen_ld32s                  TCG_HYBRID_NAME(tgen_ld32s)
#define tgen_ld32u                  TCG_HYBRID_NAME(tgen_ld32u)
#define tgen_ld8s                   TCG_HYBRID_NAME(tgen_ld8s)
#define tgen_ld8u                   TCG_HYBRID_NAME(tgen_ld8u)
#define tgen_movcond                TCG_HYBRID_NAME(tgen_movcond)
#define tgen_mul                    TCG_HYBRID_NAME(tgen_mul)
#define tgen_neg                    TCG_HYBRID_NAME(tgen_neg)
#define tgen_negsetcond             TCG_HYBRID_NAME(tgen_negsetcond)
#define tgen_not                    TCG_HYBRID_NAME(tgen_not)
#define tgen_or                     TCG_HYBRID_NAME(tgen_or)
#define tgen_orc                    TCG_HYBRID_NAME(tgen_orc)
#define tgen_ori                    TCG_HYBRID_NAME(tgen_ori)
#define tgen_qemu_ld                TCG_HYBRID_NAME(tgen_qemu_ld)
#define tgen_qemu_ld2               TCG_HYBRID_NAME(tgen_qemu_ld2)
#define tgen_qemu_st                TCG_HYBRID_NAME(tgen_qemu_st)
#define tgen_qemu_st2               TCG_HYBRID_NAME(tgen_qemu_st2)
#define tgen_rems                   TCG_HYBRID_NAME(tgen_rems)
#define tgen_remu                   TCG_HYBRID_NAME(tgen_remu)
#define tgen_rotr                   TCG_HYBRID_NAME(tgen_rotr)
#define tgen_sar                    TCG_HYBRID_NAME(tgen_sar)
#define tgen_sari                   TCG_HYBRID_NAME(tgen_sari)
#define tgen_setcond                TCG_HYBRID_NAME(tgen_setcond)
#define tgen_sextract               TCG_HYBRID_NAME(tgen_sextract)
#define tgen_shl                    TCG_HYBRID_NAME(tgen_shl)
#define tgen_shli                   TCG_HYBRID_NAME(tgen_shli)
#define tgen_shr                    TCG_HYBRID_NAME(tgen_shr)
#define tgen_shri                   TCG_HYBRID_NAME(tgen_shri)
#define tgen_sub                    TCG_HYBRID_NAME(tgen_sub)
#define tgen_xor                    TCG_HYBRID_NAME(tgen_xor)
#define tgen_xori                   TCG_HYBRID_NAME(tgen_xori)

/*
 * The external functions among them are declared under their own names in
 * tcg.h; declare the renamed copies too.
 */
void tb_target_set_jmp_target(const TranslationBlock *, int,
                              uintptr_t, uintptr_t);
int tcg_can_emit_vec_op(TCGOpcode, TCGType, unsigned);
void tcg_expand_vec_op(TCGOpcode, TCGType, unsigned, TCGArg, ...);
bool tcg_target_has_memory_bswap(MemOp);
uintptr_t tcg_qemu_tb_exec(CPUArchState *env, const void *tb_ptr);
void tcg_register_jit(const void *buf, size_t buf_size);
