/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Undoes tcg-hybrid-rename.h. */

#undef TCG_HYBRID_GLUE2
#undef TCG_HYBRID_GLUE
#undef TCG_HYBRID_NAME

#undef is_shimm16
#undef outop_add
#undef outop_addci
#undef outop_addcio
#undef outop_addco
#undef outop_and
#undef outop_andc
#undef outop_brcond
#undef outop_bswap16
#undef outop_bswap32
#undef outop_bswap64
#undef outop_clz
#undef outop_ctpop
#undef outop_ctz
#undef outop_deposit
#undef outop_divs
#undef outop_divs2
#undef outop_divu
#undef outop_divu2
#undef outop_eqv
#undef outop_extract
#undef outop_extract2
#undef outop_extrh_i64_i32
#undef outop_ld16s
#undef outop_ld16u
#undef outop_ld32s
#undef outop_ld32u
#undef outop_ld8s
#undef outop_ld8u
#undef outop_movcond
#undef outop_mul
#undef outop_muls2
#undef outop_mulsh
#undef outop_mulu2
#undef outop_muluh
#undef outop_nand
#undef outop_neg
#undef outop_negsetcond
#undef outop_nor
#undef outop_not
#undef outop_or
#undef outop_orc
#undef outop_qemu_ld
#undef outop_qemu_ld2
#undef outop_qemu_st
#undef outop_qemu_st2
#undef outop_rems
#undef outop_remu
#undef outop_rotl
#undef outop_rotr
#undef outop_sar
#undef outop_setcond
#undef outop_sextract
#undef outop_shl
#undef outop_shr
#undef outop_st
#undef outop_st16
#undef outop_st8
#undef outop_sub
#undef outop_subbi
#undef outop_subbio
#undef outop_subbo
#undef outop_xor
#undef patch_reloc
#undef tb_target_set_jmp_target
#undef tcg_can_emit_vec_op
#undef tcg_expand_vec_op
#undef tcg_out_addi_ptr
#undef tcg_out_br
#undef tcg_out_call
#undef tcg_out_dup_vec
#undef tcg_out_dupi_vec
#undef tcg_out_dupm_vec
#undef tcg_out_exit_tb
#undef tcg_out_ext16s
#undef tcg_out_ext16u
#undef tcg_out_ext32s
#undef tcg_out_ext32u
#undef tcg_out_ext8s
#undef tcg_out_ext8u
#undef tcg_out_extrl_i64_i32
#undef tcg_out_exts_i32_i64
#undef tcg_out_extu_i32_i64
#undef tcg_out_goto_ptr
#undef tcg_out_goto_tb
#undef tcg_out_ld
#undef tcg_out_mb
#undef tcg_out_mov
#undef tcg_out_movi
#undef tcg_out_movr
#undef tcg_out_nop_fill
#undef tcg_out_qemu_ld_slow_path
#undef tcg_out_qemu_st_slow_path
#undef tcg_out_set_borrow
#undef tcg_out_set_carry
#undef tcg_out_st
#undef tcg_out_sti
#undef tcg_out_tb_start
#undef tcg_out_vec_op
#undef tcg_out_xchg
#undef tcg_qemu_tb_exec
#undef tcg_register_jit
#undef tcg_target_call_iarg_regs
#undef tcg_target_call_oarg_reg
#undef tcg_target_const_match
#undef tcg_target_has_memory_bswap
#undef tcg_target_init
#undef tcg_target_op_def
#undef tcg_target_qemu_prologue
#undef tcg_target_reg_alloc_order
#undef tgen_add
#undef tgen_addi
#undef tgen_and
#undef tgen_andc
#undef tgen_andi
#undef tgen_brcond
#undef tgen_brcondi
#undef tgen_bswap16
#undef tgen_bswap32
#undef tgen_bswap64
#undef tgen_clz
#undef tgen_ctz
#undef tgen_divs
#undef tgen_divu
#undef tgen_eqv
#undef tgen_extract
#undef tgen_extrh_i64_i32
#undef tgen_ld16s
#undef tgen_ld16u
#undef tgen_ld32s
#undef tgen_ld32u
#undef tgen_ld8s
#undef tgen_ld8u
#undef tgen_movcond
#undef tgen_mul
#undef tgen_neg
#undef tgen_negsetcond
#undef tgen_not
#undef tgen_or
#undef tgen_orc
#undef tgen_ori
#undef tgen_qemu_ld
#undef tgen_qemu_ld2
#undef tgen_qemu_st
#undef tgen_qemu_st2
#undef tgen_rems
#undef tgen_remu
#undef tgen_rotr
#undef tgen_sar
#undef tgen_sari
#undef tgen_setcond
#undef tgen_sextract
#undef tgen_shl
#undef tgen_shli
#undef tgen_shr
#undef tgen_shri
#undef tgen_sub
#undef tgen_xor
#undef tgen_xori
